export default {
  ACCOUNT_PROVIDER: {
    EMAIL: 'EMAIL',
    FACEBOOK: 'FACEBOOK',
    GOOGLE: 'GOOGLE',
    TWITTER: 'TWITTER'
  },

  ERROR: {
    WRONG_LOGIN_OR_PASSWORD: 'WRONG_LOGIN_OR_PASSWORD',
    EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
    EMAIL_NOT_IN_USE: 'EMAIL_NOT_IN_USE',
    EMAIL_IS_NOT_CONFIRMED: 'EMAIL_IS_NOT_CONFIRMED',
    USERNAME_ALREADY_IN_USE: 'USERNAME_ALREADY_IN_USE',
    ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    FORBIDDEN: 'FORBIDDEN',
    WRONG_REQUEST: 'WRONG_REQUEST',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',

    ALREADY_MARKED: 'ALREADY_MARKED'
  },

  ACTIVITY_TYPE: {
    QUESTION: 'QUESTION',
    VOTE: 'VOTE',
    TAG: 'TAG',
    COMMENT: 'COMMENT',
    SOMEONE_VOTE: 'SOMEONE_VOTE',
    SOMEONE_TAG: 'SOMEONE_TAG',
    SOMEONE_COMMENT: 'SOMEONE_COMMENT',
    SOMEONE_REPLY: 'SOMEONE_REPLY',
    OTHERS_VOTE_AS_WELL: 'OTHERS_VOTE_AS_WELL'
  },

  VOTE: {
    YES: 1,
    NO: 2
  },

  TAG: {
    UNEXPECTED: 1,
    CHANGE_IN_FUTURE: 2,
    UNFAIR: 3,
    NOT_WHOLE: 4,
    PRETTY_MUCH_TRUE: 5,
    WEIRD: 6,
    EXPECTED: 7
  },

  MARK: {
    SPAM: 1,
    LIKE: 2,
    BLOCK_NOTIF: 3
  },

  MAIL_LIST: {
    SUBSCRIBERS: 'SUBSCRIBERS',
    USERS: 'USERS'
  },

  SEX: {
    MALE: 'Male',
    FEMALE: 'Female'
  },

  EDUCATION_LEVEL: {
    PRIMARY_SCHOOL: 'PrimarySchool',
    SECONDARY_SCHOOL: 'SecondarySchool',
    SPECIALIST: 'Specialist',
    BACHELOR: 'Bachelor',
    MASTER: 'Master',
    DOCTORATE: 'Doctorate'
  },

  INCOME_LEVEL: {
    MIN: 'min',
    MIDDLE: 'middle',
    MAX: 'max'
  },

  NOTIF_TYPE: {
    TRANDING: 'tranding',
    SOMEONE_COMMENT_YOUR_Q: 'comment_your_q',
    SOMEONE_COMMENT_SAME_Q: 'comment_same_q'
  },

  NOTIF_STATUS: {
    NEW: 'NEW',
    SENT: 'SENT',
    RECEIVED: 'RECEIVED',
    FAILED: 'FAILED',
    NOT_ALLOWED: 'NOT_ALLOWED'
  }
}
