export default {
  ACCOUNT_PROVIDER: {
    EMAIL: "EMAIL",
    FACEBOOK: "FACEBOOK",
    GOOGLE: "GOOGLE",
    TWITTER: "TWITTER"
  },

  ERROR: {
    WRONG_LOGIN_OR_PASSWORD: "WRONG_LOGIN_OR_PASSWORD",
    EMAIL_ALREADY_IN_USE: "EMAIL_ALREADY_IN_USE",
    EMAIL_NOT_IN_USE: "EMAIL_NOT_IN_USE",
    EMAIL_IS_NOT_CONFIRMED: "EMAIL_IS_NOT_CONFIRMED",
    USERNAME_ALREADY_IN_USE: "USERNAME_ALREADY_IN_USE",
    ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    FORBIDDEN: "FORBIDDEN",
    WRONG_REQUEST: "WRONG_REQUEST",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    NOT_FOUND: "NOT_FOUND"
  }
}
